workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios
      - pod install
      - cd ..
      - flutter build ios --no-codesign