name: plontukrot
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0' # Разрешает сборку на любой современной версии Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

  flutter_slidable: ^4.0.3
  cached_network_image: ^3.4.1
  google_sign_in: ^7.2.0

  image_picker: ^1.1.2
  auto_size_text: ^3.0.0
  intl: ^0.20.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0 # Версия 4.0.0 идеально работает с Dart 3.5.4+

flutter:
  uses-material-design: true

  fonts:
    - family: NordicStyle
      fonts:
        - asset: assets/fonts/norse.bold.otf
          weight: 700 # Bold

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  adaptive_icon_background: "#FF1E261E"
  adaptive_icon_foreground: "assets/images/app-icon.png"
