import 'plant.dart';
import '../services/genus_care_service.dart';

/// Cold-tolerance band (mirrors backend BAND_MIN_TEMP in balcony.py).
enum BalconyBand {
  frostHardy(0, -20),
  coldHardy(1, -5),
  cool(2, 4),
  moderate(3, 10),
  warm(4, 15);

  const BalconyBand(this.value, this.minTempC);
  final int value;
  final double minTempC;

  static BalconyBand? fromValue(int? v) =>
      BalconyBand.values.where((b) => b.value == v).firstOrNull;

  /// Nearest band for a given minimum temperature (°C).
  static BalconyBand nearestFor(double minTempC) {
    BalconyBand best = moderate;
    for (final band in BalconyBand.values) {
      if (minTempC <= band.minTempC) {
        best = band;
      }
    }
    return best;
  }
}

/// Resolves a plant's cold-tolerance band.
///
/// Priority:
/// 1. The plant's stored `balconyBand` (explicitly set by the user).
/// 2. The genus care guide's `min_temp_c` (generated by DeepSeek and cached
///    on the backend) — this covers plants not in the built-in table.
/// 3. A built-in genus→band table for common houseplants.
/// 4. `moderate` (+10°C) as the safe default for unknown tropicals.
class BalconyBandResolver {
  const BalconyBandResolver._();

  /// Genus (lowercased) → band. Matched by substring against the plant's
  /// genus and species, so "Hoya carnosa", "хойя", "Плющ" all resolve.
  /// Latin AND Russian names — the user's collection stores genus in Russian.
  static const Map<String, BalconyBand> _byGenus = {
    // Frost-hardy: survive deep negatives.
    'hedera': BalconyBand.frostHardy, // плющ, -20°C
    'плющ': BalconyBand.frostHardy,
    // Cold-hardy: survive light frost.
    'cycas': BalconyBand.coldHardy, // саговник, -5°C
    'саговник': BalconyBand.coldHardy,
    'oxalis': BalconyBand.coldHardy, // кислица, -5°C
    'кислица': BalconyBand.coldHardy,
    // Cool: survive a few degrees above zero.
    'dichondra': BalconyBand.cool, // +4°C
    'дихондра': BalconyBand.cool,
    // Warm: need +15°C.
    'anthurium': BalconyBand.warm, // +15°C
    'антуриум': BalconyBand.warm,
  };

  /// Resolve the band for a plant.
  ///
  /// Priority:
  /// 1. The plant's stored `balconyBand` (explicitly set by the user).
  /// 2. The built-in genus table (Latin + Russian) — authoritative for known
  ///    genera, so DeepSeek can't override e.g. плющ → +15°C.
  /// 3. The genus care guide's `min_temp_c` (DeepSeek) for unknown genera.
  /// 4. `moderate` (+10°C) as the safe default.
  static Future<BalconyBand> resolve(Plant plant) async {
    final stored = BalconyBand.fromValue(plant.balconyBand);
    if (stored != null) return stored;

    // Built-in table first — authoritative for known genera.
    final haystack =
        '${plant.genus} ${plant.species} ${plant.plantFamily ?? ''}'
            .toLowerCase();
    for (final entry in _byGenus.entries) {
      if (haystack.contains(entry.key)) return entry.value;
    }

    // Unknown genus → ask the DeepSeek care guide (cached on backend).
    final genus = plant.genus.trim();
    if (genus.isNotEmpty) {
      try {
        final guide = await GenusCareService().getCareGuide(
          genus,
          locale: 'ru',
        );
        final minTemp = guide?.minTempC;
        if (minTemp != null) {
          return BalconyBand.nearestFor(minTemp);
        }
      } catch (_) {
        // Fall through to the safe default on any error.
      }
    }
    return BalconyBand.moderate;
  }
}
