# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats so ensure you're okay with it
plugin 'cocoapods-art' if Build.env['COCOAPODS_ART']

# Automatically framework setups
install! 'cocoapods', :deterministic_uuids => false

# This block reads Flutter's internal build configs
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Force deployment target to 15.0 for all plugins
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
