name: iOS Flutter Build

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Update CocoaPods Dependencies
        run: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

#      - name: Build iOS IPA (no codesign)
#
#        run: flutter build ipa --debug --no-codesign
#
#      - name: Upload iOS Build Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ios-debug-ipa
#
#          path: build/ios/ipa/*.ipa
      - name: Build iOS Simulator App
        run: flutter build ios --debug --simulator --no-codesign

      - name: Zip and Upload App for Appetize
        uses: actions/upload-artifact@v4
        with:
          name: appetize-ios-build
          path: build/ios/iphonesimulator/Runner.app
